version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://auttapon:password@mysql:3306/mydb_niyom
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydb_niyom
      MYSQL_USER: auttapon
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
