version: '3.9'

services:
  app:
    container_name: 'niyom_app_server'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:8000' # Map port 3000 ของ host กับ port 8000 ของ container
    env_file:
      - .env # ใช้ไฟล์ .env สำหรับการตั้งค่าตัวแปรสภาพแวดล้อม


volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
