version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8080" # map จาก port Dockerfile
    environment:
      DATABASE_URL: mysql://root:P@ssw0rd@localhost:3307/mydb_niyom
      JWT_SECRET_KEY: "secretKeyRandom"
      JWT_EXPIRES_IN: "30d"
    volumes:
      - ./:/app
      - /app/node_modules
    # restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      DATABASE_URL: mysql://root:P@ssw0rd@localhost:3307/mydb_niyom
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydb_niyom
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
