name: Deploy Niyom App Server

on:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t niyom_app_server:${{ github.sha }} .

      - name: Save Docker image as tar
        run: |
          docker save niyom_app_server:${{ github.sha }} -o niyom_app_server.tar
          chmod 644 niyom_app_server.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'niyom_app_server.tar'
          target: '/var/www/niyom_app_server/'

      - name: Load Docker image and run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/niyom_app_server
            docker load -i niyom_app_server.tar
            docker stop niyom_app_server || true
            docker rm niyom_app_server || true
            docker run -d -p 8000:8000 --name niyom_app_server niyom_app_server:${{ github.sha }}
